---
- name: Setting ansible_ssh_common_args when ssh_proxy is defined
  set_fact:
    ansible_ssh_common_args: "{{ ssh_args }}"
  when: ssh_proxy is defined

- name: Setting 'group_names' fact for {{ inventory_hostname }}
  set_fact:
    group_names: "{{ group_names }}"
    cacheable: yes

- name: Obtaining `swversion` of {{ inventory_hostname }}
  shell: "sudo /opt/Avaya/bin/swversion"
  register: swversion_output

- name: Setting 'swversion' fact for {{ inventory_hostname }}
  set_fact:
    swversion: "{{ swversion_output.stdout }}"
    cacheable: yes

- name: Obtaining last 10 backups from 'zr_backuprestore' of {{ inventory_hostname }}
  become: yes
  shell: mgmtia -t asm -AtF'|' -c "select service_name,cluster_name,file_name,path_on_server from zr_backuprestore where operation='backup' order by completed_time DESC limit 10"
  register: backup_status_output
  when: ansible_become_pass is defined

- name: Setting 'backup_status' fact for {{ inventory_hostname }}
  set_fact:
    backup_status: "{{ backup_status_output.stdout }}"
    cacheable: yes
  when: ansible_become_pass is defined

- name: Obtaining `deploy_service -lv` of {{ inventory_hostname }}
  shell: "sudo /opt/Avaya/aura/bin/deploy_service.sh -lv"
  register: deploy_service_output

- name: Setting 'deploy_service' fact for {{ inventory_hostname }}
  set_fact:
    deploy_service: "{{ deploy_service_output.stdout }}"
    cacheable: yes

- name: Obtaining `statapp` of {{ inventory_hostname }}
  shell: "/opt/Avaya/bin/statapp"
  register: statapp_output

- name: Setting 'statapp' fact for {{ inventory_hostname }}
  set_fact:
    statapp: "{{ statapp_output.stdout }}"
    cacheable: yes

- name: Obtaining `ceconfig` of {{ inventory_hostname }}
  become: yes
  shell: "sudo /opt/Avaya/bin/ceconfig"
  register: ceconfig_output
  when: ansible_become_pass is defined

- name: Setting 'ceconfig' fact for {{ inventory_hostname }}
  set_fact:
    ceconfig: "{{ ceconfig_output.stdout }}"
    cacheable: yes
  when: ansible_become_pass is defined

- name: Obtaining certificates of {{ inventory_hostname }}
  vars:
    secmodip_regex: "Local Security Module: ([^ \n]+)"
    secmodip: "{{ ceconfig_output.stdout | regex_search(secmodip_regex, '\\1') | first }}"
  get_certs:
    name: "{{ item.name }}"
    host: "{{ item.host }}"
    port: "{{ item.port }}"
    starttls: "{{ item.starttls }}"
  with_items:
    - { name: "securitymodule_sip", host: "127.0.0.2", port: 15061 , starttls: "" }
    - { name: "securitymodule_http", host: "{{ secmodip }}", port: 443, starttls: "" }
    - { name: "mgmt", host: "{{ ansible_host }}", port: 2009, starttls: "" }
    - { name: "postgres", host: "127.0.0.1", port: 5432, starttls: "postgres" }
  register: get_certs_output

- name: Setting 'certificates' fact for {{ inventory_hostname }}
  set_fact:
    certificates: "{{ certificates | default({}) | combine({ item.1: get_certs_output.results[item.0][item.1] }) }}"
    cacheable: yes
  with_indexed_items:
    - "securitymodule_sip"
    - "securitymodule_http"
    - "mgmt"
    - "postgres"

# - name: Obtaining syslog certificates of {{ inventory_hostname }}
#   become: yes
#   slurp:
#     src: $JBOSS_HOME/standalone/configuration/tm/keystore/syslog_keystore.pem
#   register: syslog_keystore
#   when: ansible_become_pass is defined

# - name: Adding syslog certificate to 'certificates' fact for {{ inventory_hostname }}
#   vars:
#     syslog_keystore_regex: "(-----BEGIN CERTIFICATE-----.+?-----END CERTIFICATE-----)"
#     syslog_keystore_cert: "{{ syslog_keystore['content'] | b64decode | regex_findall(syslog_keystore_regex) }}"
#   set_fact:
#     certificates: "{{ certificates | default({}) | combine({ 'syslog': syslog_keystore_cert }) }}"
#     cacheable: yes
#   when: ansible_become_pass is defined
...