---
-
  hosts: localhost
  connection: local
  gather_facts: False

  # vars
  vars:
    timeout: 80
    default: ""
    swversion_stdout: swversions.csv

  # tasks
  tasks:
    - include_tasks: tasks/swversion_create_csv.yml

-
  #### Enabling SSH to AVP ####
  hosts: AVPU
  gather_facts: False
  ignore_unreachable: true
  ignore_errors: true

  # vars: variables that will apply to the play
  vars:
    timeout: 80

  tasks:
    - include_tasks: tasks/swversion_avp_ssh_enable.yml

- 
  #### AADS ####
  hosts: AADS
  gather_facts: False
  ignore_unreachable: true
  ignore_errors: true

  # vars: variables that will apply to the play
  vars:
    timeout: 80
    default: ""
    swversion_stdout: swversions.csv

  tasks:
    - include_tasks: tasks/swversion_avaya_aads.yml

-
  #### AAMS ####
  hosts: AAMS
  gather_facts: False
  ignore_unreachable: true
  ignore_errors: true

  # vars: variables that will apply to the play
  vars:
    timeout: 80
    default: ""
    swversion_stdout: swversions.csv

  tasks:
    - include_tasks: tasks/swversion_avaya_aams.yml

- 
  #### ADS ####
  hosts: ADS
  gather_facts: False
  ignore_unreachable: true
  ignore_errors: true

  # vars: variables that will apply to the play
  vars:
    timeout: 80
    default: ""
    swversion_stdout: swversions.csv

  tasks:
    - include_tasks: tasks/swversion_avaya_ads.yml

-
  #### AES ####
  hosts: AES
  gather_facts: False
  ignore_unreachable: true
  ignore_errors: true

  # vars: variables that will apply to the play
  vars:
    timeout: 80
    default: ""
    swversion_stdout: swversions.csv

  tasks:
    - include_tasks: tasks/swversion_avaya_aes.yml

-
  #### SBCE ####
  hosts: SBCE
  gather_facts: False
  ignore_unreachable: true
  ignore_errors: true

  # vars: variables that will apply to the play
  vars:
    timeout: 80
    default: ""
    swversion_stdout: swversions.csv

  tasks:
    - include_tasks: tasks/swversion_avaya_sbce.yml

-
  #### BGW ####
  hosts: BGW
  gather_facts: False
  ignore_unreachable: true
  ignore_errors: true

  # vars: variables that will apply to the play
  vars:
    timeout: 80
    default: ""
    swversion_stdout: swversions.csv

  tasks:
    - include_tasks: tasks/swversion_avaya_bgw.yml

-
  #### ASP ####
  hosts: asp
  gather_facts: False
  ignore_unreachable: true
  ignore_errors: true

  # vars: variables that will apply to the play
  vars:
    timeout: 80
    default: ""
    swversion_stdout: swversions.csv

  tasks:
    - include_tasks: tasks/swversion_avaya_asp.yml

-
  #### AVP ####
  hosts: avp
  gather_facts: False
  ignore_unreachable: true
  ignore_errors: true

  # vars: variables that will apply to the play
  vars:
    timeout: 80
    default: ""
    swversion_stdout: swversions.csv

  tasks:
    - include_tasks: tasks/swversion_avaya_avp.yml

-
  #### AVPU ####
  hosts: AVPU
  gather_facts: False
  ignore_unreachable: true
  ignore_errors: true

  # vars: variables that will apply to the play
  vars:
    timeout: 80
    default: ""
    swversion_stdout: swversions.csv

  tasks:
    - include_tasks: tasks/swversion_avaya_avpu.yml

-
  #### CM ####
  hosts: CM
  gather_facts: False
  ignore_unreachable: true
  ignore_errors: true

  # vars: variables that will apply to the play
  vars:
    timeout: 80
    default: ""
    swversion_stdout: swversions.csv

  tasks:
    - include_tasks: tasks/swversion_avaya_cm.yml

-
  #### SMGR ####
  hosts: SMGR
  gather_facts: False
  ignore_unreachable: true
  ignore_errors: true

  # vars: variables that will apply to the play
  vars:
    timeout: 80
    default: ""
    swversion_stdout: swversions.csv

  tasks:
    - include_tasks: tasks/swversion_avaya_smgr.yml

- 
  #### SM ####
  hosts: SM
  gather_facts: False
  ignore_unreachable: true
  ignore_errors: true

  # vars: variables that will apply to the play
  vars:
    timeout: 80
    default: ""
    swversion_stdout: swversions.csv

  # tasks
  tasks:
    - include_tasks: tasks/swversion_avaya_sm.yml

-
  #### BREEZE ####
  hosts: BREEZE
  gather_facts: False
  ignore_unreachable: true
  ignore_errors: true

  # vars: variables that will apply to the play
  vars:
    timeout: 80
    default: ""
    swversion_stdout: swversions.csv

  tasks:
    - include_tasks: tasks/swversion_avaya_breeze.yml
...
