---
-
  hosts: localhost
  connection: local
  gather_facts: False

  # vars
  vars:
    swversion_stdout: swversions.csv

  # tasks
  tasks:
    - include_tasks: tasks/swversion_create_csv.yml

-
  #### CM ####
  hosts: all
  gather_facts: False
  ignore_unreachable: true
  ignore_errors: true

  # vars: variables that will apply to the play
  vars:
    timeout: 15
    default: ""
    swversion_stdout: swversions.csv
    latest_cm_appsp: "8.1.3.6.0.890.27674"
    latest_cm_ssp: "PLAT-rhel7.6-0270"
    latest_cm_ksp: "KERNEL-3.10.0-1160.80.1.el7"

  tasks:
    - include_tasks: test_cm.yml
      when: "'CM' in group_names"
...