---
# - hosts: SMGR
#   gather_facts: False
#   ignore_unreachable: true
#   ignore_errors: true
#   roles:
#     - base
#     - smgr

# - hosts: SM
#   gather_facts: False
#   ignore_unreachable: true
#   ignore_errors: true
#   roles:
#     - base
#     - sm

# - hosts: AADS
#   gather_facts: False
#   ignore_unreachable: true
#   ignore_errors: true
#   roles:
#     - base
#     - aads

# - hosts: CM
#   gather_facts: False
#   ignore_unreachable: true
#   ignore_errors: true
#   roles: 
#     - cm

- hosts: AVP
  gather_facts: False
  ignore_unreachable: true
  ignore_errors: true
  roles:
    - avp

- hosts: BREEZE
  gather_facts: False
  ignore_unreachable: true
  ignore_errors: true
  roles:
    - base
    - breeze
...