---
# - hosts: sd36smgr1
#   gather_facts: False
#   ignore_unreachable: true
#   ignore_errors: true
#   roles:
#     - base
#     - smgr

# - hosts: sd36sm1
#   gather_facts: False
#   ignore_unreachable: true
#   ignore_errors: true
#   roles:
#     - base
#     - sm

# - hosts: sd36aads1
#   gather_facts: False
#   ignore_unreachable: true
#   ignore_errors: true
#   roles:
#     - base
#     - aads

# - hosts: sd36cm1
#   gather_facts: False
#   ignore_unreachable: true
#   ignore_errors: true
#   roles:
#     - base
#     - cm

# - hosts: AVP
#   gather_facts: False
#   ignore_unreachable: true
#   ignore_errors: true
#   roles:
#     - esxi  
#     - avp

# - hosts: AVPU
#   gather_facts: False
#   ignore_unreachable: true
#   ignore_errors: true
#   roles:
#     - base 
#     - avpu

# - hosts: BREEZE
#   gather_facts: False
#   ignore_unreachable: true
#   ignore_errors: true
#   roles:
#     - base
#     - breeze

# - hosts: g450
#   gather_facts: False
#   ignore_unreachable: true
#   ignore_errors: true
#   roles:
#     - bgw

- hosts: SBCE
  gather_facts: False
  ignore_unreachable: true
  ignore_errors: true
  roles:
    - base
    - sbce

# - hosts: sd36aams2
#   gather_facts: False
#   ignore_unreachable: true
#   ignore_errors: true
#   roles:
#     - base
#     - aams

# - hosts: AES
#   gather_facts: False
#   ignore_unreachable: true
#   ignore_errors: true
#   roles:
#     - base
#     - aes

# - hosts: ADS
#   gather_facts: False
#   ignore_unreachable: true
#   ignore_errors: true
#   roles:
#     - base
#     - ads
...
