# Every YAML file should start with three dashes
---
-
  # Hosts: where our play will run and options it will run with
  hosts: all
  gather_facts: no
  #connection: local
  # Vars: variables that will apply to the play, on all target systems
  
  # Tasks: the list of tasks that will be executed within the playbook
  tasks:
    - name: get uname
      uname:
      register: rv

    - name: append to logs
      lineinfile:
        line: "{{ ansible_host }}: '{{ rv.uname[0] }}'"
        insertafter: EOF
        dest: logs
      delegate_to: localhost

...