---
- name: Setting ansible_ssh_common_args when ssh_proxy is defined
  set_fact:
    ansible_ssh_common_args: "{{ ssh_args }}"
  when: ssh_proxy is defined

- name: Obtaining `vim-cmd vimsvc/license` for {{ inventory_hostname }}
  shell: "vim-cmd vimsvc/{{ item }}"
  with_items:
    - "license"
  register: vim_cmd_vimsvc_output

- name: Setting 'vim_cmd_vimsvc' fact for {{ inventory_hostname }}
  set_fact:
    vim_cmd_vimsvc: "{{ vim_cmd_vimsvc | default({}) | combine({ item.item: item.stdout }) }}"
    cacheable: yes
  with_items: "{{ vim_cmd_vimsvc_output.results }}"
...