---
- name: Setting ansible_ssh_common_args when ssh_proxy is defined
  set_fact:
    ansible_ssh_common_args: "{{ ssh_args }}"
  when: ssh_proxy is defined

- name: Obtaining AVP `swversion` output
  vars:
    cmd: "/opt/avaya/bin/swversion"
  shell: "{{ cmd }}"
  timeout: "{{ timeout }}"
  register: result
  tags:
    - AVP

- name: Extracting AVP Release
  vars:
    appsp_regex: "Release: ([^ \n]+)"
    appsp_res: "{{ result.stdout | regex_search(appsp_regex, '\\1') }}"
  set_fact:
    appsp: "{{ appsp_res | first }}"
  when: (appsp_res | length >= 1) and (result is defined)
  delegate_to: localhost
  tags:
    - AVP

- name: Extracting AVP SSP version
  vars:
    ssp_regex: "Security Service Patch.*-0?([0-9]*)"
    ssp_res: "{{ result.stdout | regex_search(ssp_regex, '\\1') }}"
  set_fact:
    ssp: "{{ ssp_res | first }}"
  when: ssp_res | length >= 1
  delegate_to: localhost
  tags:
    -  AVP

- name: Writting AVP latest versions to '{{ swversion_stdout }}'
  lineinfile:
    line: "AVAYA VIRTUALIZATION PLATFORM,Latest,AVP,,{{ latest_avp_appsp | default('') }},,{{ latest_avp_ssp | default('') }},"
    insertafter: EOF
    dest: "{{ swversion_stdout }}"
  delegate_to: localhost
  tags:
    - AVP

- name: Writting AVP extracted versions to '{{ swversion_stdout }}'
  vars:
    pgrp: "{{ group_names | first | default('') }}"
    cgrp: "{{ group_names | last | default('') }}"
    syssp: ""
    ksp: ""
  lineinfile:
    line: "{{ inventory_hostname }},{{ ansible_host }},{{ pgrp }},{{ cgrp }},{{ appsp }},{{ syssp }},{{ ssp }},{{ ksp }}"
    insertafter: EOF
    dest: "{{ swversion_stdout }}"
  delegate_to: localhost
  tags:
    - AVP

- name: Resetting SSH connection
  ansible.builtin.meta: reset_connection
...