---
- name: Obtaining Breeze `swversion` output
  command: sudo /opt/Avaya/bin/swversion
  register: swversion
  tags:
    - breeze

- name: Extracting Breeze `Release`
  vars:
    appsp_regex: "Release: ([^ \n]+)"
  set_fact:
    appsp: "{{ swversion.stdout | regex_search(appsp_regex, '\\1') | first }}"
  tags:
    - breeze

- name: Dumping Breeze header to '{{ swversion_stdout }}'
  lineinfile:
    line: "BREEZE,Latest,BREEZE,,{{ latest_breeze_appsp }},,,"
    insertafter: EOF
    dest: "{{ swversion_stdout }}"
  delegate_to: localhost
  tags:
    - breeze

- name: Dumping Breeze version to '{{ swversion_stdout }}'
  vars:
    pgrp: "{{ group_names | first | default('') }}"
    cgrp: "{{ group_names | last | default('') }}"
    syssp: ""
    ssp: ""
    ksp: ""
  lineinfile:
    line: "{{ inventory_hostname }},{{ ansible_host }},{{ pgrp }},{{ cgrp }},{{ appsp }},{{ syssp }},{{ ssp }},{{ ksp }}"
    insertafter: EOF
    dest: "{{ swversion_stdout }}"
  delegate_to: localhost
  ignore_errors: true
  tags:
    - breeze
...