---
- name: Checking if '{{ swversion_stdout }}' exists
  stat:
    path: "{{ swversion_stdout }}"
  register: stat_result
  delegate_to: localhost
  tags:
    - always

- name: Renaming '{{ swversion_stdout }}' to '{{ swversion_stdout }}.prev'
  copy:
    src: "{{ swversion_stdout }}"
    dest: "{{ swversion_stdout }}.prev"
  when: stat_result.stat.exists
  delegate_to: localhost
  tags:
    - always

- name: Creating new '{{ swversion_stdout }}'
  copy:
    content: 'Name,IP,Type,SubType,Application,System/Hardware,Security Service Pack,Kernel Service Pack'
    dest: "{{ swversion_stdout }}"
  delegate_to: localhost
  tags:
    - always
...