---
- name: Setting ansible_ssh_common_args when ssh_proxy is defined
  set_fact:
    ansible_ssh_common_args: "{{ ssh_args }}"
  when: ssh_proxy is defined

- name: Obtaining ADS `swversion` output
  vars:
    cmd: "swversion"
  shell: "{{ cmd }}"
  become: yes
  timeout: "{{ timeout }}"
  register: result
  tags:
    - ADS

- name: Extracting SLAMon Server Version
  vars:
    slamon_appsp_regex: "SLAMon Server Version: ([^ \n]+)"
    slamon_appsp: "{{ result.stdout | regex_search(slamon_appsp_regex, '\\1') }}"
  set_fact:
    slamon_appsp: "{{ slamon_appsp | first }}"
  when: slamon_appsp | length >= 1
  tags:
    - ADS

- name: Extracting SAL Gateway Version
  vars:
    salgw_appsp_regex: "SAL Gateway Version: ([^ \n]+)"
    salgw_appsp: "{{ result.stdout | regex_search(salgw_appsp_regex, '\\1') }}"
  set_fact:
    salgw_appsp: "{{ salgw_appsp | first }}"
  when: salgw_appsp | length >= 1
  tags:
    - ADS

- name: Writting SLAMon latest version to '{{ swversion_stdout }}'
  vars:
  lineinfile:
    line: "AVAYA DIAGNOSTIC SERVER,Latest,ADS,slamon,{{ latest_slamon_appsp | default('') }},,,"
    insertafter: EOF
    dest: "{{ swversion_stdout }}"
  delegate_to: localhost
  when: slamon_appsp is defined
  tags:
    - ADS

- name: Writting SLAMon extracted version '{{ swversion_stdout }}'
  vars:
    pgrp: "{{ group_names | first | default('') }}"
    cgrp: "{{ group_names | last | default('') }}"
    appsp: "{{ slamon_appsp }}"
    syssp: ""
    ssp: ""
    ksp: ""
  lineinfile:
    line: "{{ inventory_hostname }},{{ ansible_host }},{{ pgrp }},{{ cgrp }},{{ appsp }},{{ syssp }},{{ ssp }},{{ ksp }}"
    insertafter: EOF
    dest: "{{ swversion_stdout }}"
  delegate_to: localhost
  when: slamon_appsp is defined
  tags:
    - ADS

- name: Writting SAL Gateway latest version to '{{ swversion_stdout }}'
  lineinfile:
    line: "AVAYA DIAGNOSTIC SERVER,Latest,ADS,salgw,{{ latest_salgw_appsp | default('') }},,,"
    insertafter: EOF
    dest: "{{ swversion_stdout }}"
  delegate_to: localhost
  when: salgw_appsp is defined
  tags:
    - ADS

- name: Writting SAL Gateway extracted version to '{{ swversion_stdout }}'
  vars:
    pgrp: "{{ group_names | first | default('') }}"
    cgrp: "{{ group_names | last | default('') }}"
    appsp: "{{ salgw_appsp }}"
    syssp: ""
    ssp: ""
    ksp: ""
  lineinfile:
    line: "{{ inventory_hostname }},{{ ansible_host }},{{ pgrp }},{{ cgrp }},{{ appsp }},{{ syssp }},{{ ssp }},{{ ksp }}"
    insertafter: EOF
    dest: "{{ swversion_stdout }}"
  delegate_to: localhost
  when: salgw_appsp is defined
  tags:
    - ADS

- name: Resetting SSH connection
  ansible.builtin.meta: reset_connection
...