---
- name: Setting ansible_ssh_common_args when ssh_proxy is defined
  set_fact:
    ansible_ssh_common_args: "{{ ssh_args }}"
  when: ssh_proxy is defined

- name: Obtaining SMGR `swversion` output
  vars:
    cmd: "sh /opt/Avaya/vsp/swversion.sh"
  shell: "{{ cmd }}"
  timeout: "{{ timeout }}"
  register: result
  tags:
    - SMGR

- name: Extracting SMGR RTS Version
  vars:
    appsp_regex: "RTS Version: SMGR ([^ \n]+)"
    appsp_res: "{{ result.stdout | regex_search(appsp_regex, '\\1') }}"
  set_fact:
    appsp: "{{ appsp_res | first }}"
  when: (appsp_res | length >= 1) and (result is defined)
  delegate_to: localhost
  tags:
    - SMGR

- name: Setting pre10 variable based on SMGR major release
  vars:
    pre10_regex: "([876]+)"
    pre10_res: "{{ appsp | regex_search(pre10_regex, '\\1') }}"
  set_fact:
    pre10: "{% if ((pre10_res | length >= 1) and (pre10_res | first | int < 10)) %}True{% else %}False{% endif %}"
  delegate_to: localhost
  tags:
    - SMGR 

- name: Extracting pre 10 SMGR SSP version
  vars:
    ssp1_regex: "SMGR SSP [^\n]+\nPatch 8.1.7.81([0-9][0-9])"
    ssp1_res: "{{ result.stdout | regex_search(ssp1_regex, '\\1') }}"
  set_fact:
    ssp1: "{{ ssp1_res | first }}"
  when: (pre10) and (ssp1_res | length >= 1)
  delegate_to: localhost
  tags:
    - SMGR

- name: Extracting SMGR SSP version
  vars:
    ssp2_regex: "AV_SSP_VERSION : ([0-9]*)"
    ssp2_res: "{{ result.stdout | regex_search(ssp2_regex, '\\1') }}"
  set_fact:
    ssp2: "{{ ssp2_res | first }}"
  when: (not pre10) and (ssp2_res | length >= 1)
  delegate_to: localhost
  tags:
    - SMGR

- name: Setting SMGR SSP version
  set_fact:
    ssp: "{{ ssp1 if (ssp1 is defined) else ssp2 }}"
  delegate_to: localhost
  tags:
    - SMGR

- name: Writting SMGR latest versions to '{{ swversion_stdout }}'
  lineinfile:
    line: "SYSTEM MANAGER,Latest,SMGR,,{{ latest_smgr_appsp }},,{{ latest_smgr_ssp }},"
    insertafter: EOF
    dest: "{{ swversion_stdout }}"
  delegate_to: localhost
  tags:
    - SMGR

- name: Writting SMGR extracted versions to '{{ swversion_stdout }}'
  vars:
    pgrp: "{{ group_names | first | default('') }}"
    cgrp: "{{ group_names | last | default('') }}"
    syssp: ""
    ksp: ""
  lineinfile:
    line: "{{ inventory_hostname }},{{ ansible_host }},{{ pgrp }},{{ cgrp }},{{ appsp }},{{ syssp }},{{ ssp }},{{ ksp }}"
    insertafter: EOF
    dest: "{{ swversion_stdout }}"
  delegate_to: localhost
  tags:
    - SMGR

- name: Resetting SSH connection
  ansible.builtin.meta: reset_connection
...