---
- name: Setting ansible_ssh_common_args when ssh_proxy is defined
  set_fact:
    ansible_ssh_common_args: "{{ ssh_args }}"
  when: ssh_proxy is defined

- name: Obtaining Breeze `swversion` output
  vars:
    cmd: "sudo /opt/Avaya/bin/swversion"
  shell: "{{ cmd }}"
  timeout: "{{ timeout }}"
  register: result
  tags:
    - BREEZE

- name: Extracting Breeze Release
  vars:
    appsp_regex: "Release: ([^ \n]+)"
    appsp_res: "{{ result.stdout | regex_search(appsp_regex, '\\1') }}"
  set_fact:
    appsp: "{{ appsp_res | first }}"
  when: (appsp_res | length >= 1) and (result is defined)
  delegate_to: localhost
  tags:
    - BREEZE

- name: Writting Breeze latest versions to '{{ swversion_stdout }}'
  lineinfile:
    line: "BREEZE,Latest,BREEZE,,{{ latest_breeze_appsp | default('') }},,,"
    insertafter: EOF
    dest: "{{ swversion_stdout }}"
  delegate_to: localhost
  tags:
    - BREEZE

- name: Writting Breeze extracted versions to '{{ swversion_stdout }}'
  vars:
    pgrp: "{{ group_names | first | default('') }}"
    cgrp: "{{ group_names | last | default('') }}"
    syssp: ""
    ssp: ""
    ksp: ""
  lineinfile:
    line: "{{ inventory_hostname }},{{ ansible_host }},{{ pgrp }},{{ cgrp }},{{ appsp }},{{ syssp }},{{ ssp }},{{ ksp }}"
    insertafter: EOF
    dest: "{{ swversion_stdout }}"
  delegate_to: localhost
  tags:
    - BREEZE

- name: Obtaining Breeze `deploy_service -lv` output
  vars:
    cmd: "sudo /opt/Avaya/aura/bin/deploy_service.sh -lv"
  shell: "{{ cmd }}"
  timeout: "{{ timeout }}"
  register: services
  tags:
    - BREEZE

- name: Extracting Attendant version
  vars:
    attsp_regex: "Attendant-(.*)"
    attsp_res: "{{ services.stdout | regex_search(attsp_regex, '\\1') }}"
  set_fact:
    attsp: "{{ attsp_res | first }}"
  when: (attsp_res | length >= 1) and (services is defined)
  delegate_to: localhost
  tags:
    - BREEZE

- name: Writting Attendant latest versions to '{{ swversion_stdout }}'
  lineinfile:
    line: "ATTENDANT SNAP-IN,Latest,BREEZE,,{{ latest_attendant_attsp | default('') }},,,"
    insertafter: EOF
    dest: "{{ swversion_stdout }}"
  when: attsp is defined
  delegate_to: localhost
  tags:
    - BREEZE

- name: Writting Attendant extracted versions to '{{ swversion_stdout }}'
  vars:
    pgrp: "{{ group_names | first | default('') }}"
    cgrp: "attendant"
    syssp: ""
    ssp: ""
    ksp: ""
  lineinfile:
    line: "{{ inventory_hostname }},{{ ansible_host }},{{ pgrp }},{{ cgrp }},{{ attsp }},{{ syssp }},{{ ssp }},{{ ksp }}"
    insertafter: EOF
    dest: "{{ swversion_stdout }}"
  when: attsp is defined
  delegate_to: localhost
  tags:
    - BREEZE

- name: Extracting PresenceServices version
  vars:
    pssp_regex: "PresenceServices-(.*)"
    pssp_res: "{{ services.stdout | regex_search(pssp_regex, '\\1') }}"
  set_fact:
    pssp: "{{ pssp_res | first }}"
  when: (pssp_res | length >= 1) and (services is defined)
  delegate_to: localhost
  tags:
    - BREEZE

- name: Writting Presence latest versions to '{{ swversion_stdout }}'
  lineinfile:
    line: "PRESENCE SNAP-IN,Latest,BREEZE,,{{ latest_presence_pssp | default('') }},,,"
    insertafter: EOF
    dest: "{{ swversion_stdout }}"
  when: pssp is defined
  delegate_to: localhost
  tags:
    - BREEZE

- name: Writting Presence extracted versions to '{{ swversion_stdout }}'
  vars:
    pgrp: "{{ group_names | first | default('') }}"
    cgrp: "presence"
    syssp: ""
    ssp: ""
    ksp: ""
  lineinfile:
    line: "{{ inventory_hostname }},{{ ansible_host }},{{ pgrp }},{{ cgrp }},{{ pssp }},{{ syssp }},{{ ssp }},{{ ksp }}"
    insertafter: EOF
    dest: "{{ swversion_stdout }}"
  when: pssp is defined
  delegate_to: localhost
  tags:
    - BREEZE

- name: Resetting SSH connection
  ansible.builtin.meta: reset_connection
  when: ssh_proxy is defined
...