---
- name: Setting ansible_ssh_common_args when ssh_proxy is defined
  set_fact:
    ansible_ssh_common_args: "{{ ssh_args }}"
  when: ssh_proxy is defined

- name: AVP_SSH_enable
  vars:
    cmd: "/opt/avaya/common_services/AVP_SSH enable"
  shell: "{{ cmd }}"
  timeout: "{{ timeout }}"
  register: result
  tags:
    - AVPU

- name: Resetting SSH connection
  ansible.builtin.meta: reset_connection
  when: ssh_proxy is defined
...
