---
-
  hosts: AvayaG450A
  gather_facts: false

  tasks:
    - name: Obtain `show system` output
      avaya_bgw_raw:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        cmd: "show system"
      register: sysinfo
      delegate_to: localhost
      no_log: true
      tags:
        - g4xx
    
    - name: Extracting 'Mainboard FW Vintage'
      vars:
        fw_regex: "Mainboard FW Vintage    : ([^ \n]+)"
      set_fact:
        fw: "{{ sysinfo.stdout | regex_search(fw_regex, '\\1') | first }}"
      tags:
        - g4xx

    - name: Displaying firmware version
      debug:
        var: fw
      tags:
        - g4xx
...