---
- name: Setting ansible_ssh_common_args when ssh_proxy is defined
  set_fact:
    ansible_ssh_common_args: "{{ ssh_args }}"
  when: ssh_proxy is defined

- name: Obtaining AES `swversion` output
  vars:
    cmd: "swversion"
  shell: "{{ cmd }}"
  timeout: "{{ timeout }}"
  register: result
  tags:
    - AES

- name: Extracting AES Version
  vars:
    appsp_regex: "Version: ([^ \n]+)"
    appsp_res: "{{ result.stdout | regex_search(appsp_regex, '\\1') }}"
  set_fact:
    appsp: "{{ appsp_res | first }}"
  when: (appsp_res | length >= 1) and (result is defined)
  delegate_to: localhost
  tags:
    - AES

- name: Extracting AES SSP version
  vars:
    ssp_regex: "(LSU-[^ \n]+)"
    ssp_res: "{{ result.stdout | regex_search(ssp_regex, '\\1') }}"
  set_fact:
    ssp: "{{ ssp_res | first }}"
  when: ssp_res | length >= 1
  delegate_to: localhost
  tags:
    - AES

- name: Writting AES latest versions to '{{ swversion_stdout }}'
  lineinfile:
    line: "APPLICATION ENABLEMENT SERVICES,Latest,AES,,{{ latest_aes_appsp | default('') }},,{{ latest_aes_ssp | default('') }},"
    insertafter: EOF
    dest: "{{ swversion_stdout }}"
  delegate_to: localhost
  tags:
    - AES

- name: Writting AES extracted versions to '{{ swversion_stdout }}'
  vars:
    pgrp: "{{ group_names | first | default('') }}"
    cgrp: "{{ group_names | last | default('') }}"
    syssp: ""
    ksp: ""
  lineinfile:
    line: "{{ inventory_hostname }},{{ ansible_host }},{{ pgrp }},{{ cgrp }},{{ appsp }},{{ syssp }},{{ ssp }},{{ ksp }}"
    insertafter: EOF
    dest: "{{ swversion_stdout }}"
  delegate_to: localhost
  tags:
    - AES

- name: Resetting SSH connection
  ansible.builtin.meta: reset_connection
...