---
- name: Obtaining Gxxx `show system` output
  avaya_bgw_raw:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    cmd: "show system"
  register: system
  delegate_to: localhost
  no_log: true
  tags:
    - gxxx

- name: Extracting FW Vintage
  vars:
    appsp_regex: ".*FW Vintage.*: ([^ \n]+)"
  set_fact:
    appsp: "{{ system.stdout | regex_search(appsp_regex, '\\1') | first }}"
  tags:
    - gxxx

- name: Extracting HW Vintage
  vars:
    syssp_regex: ".*HW Vintage.*: ([^ \n]+)"
  set_fact:
    syssp: "HW Vintage {{ system.stdout | regex_search(syssp_regex, '\\1') | first }}"
  tags:
    - gxxx

- name: Dumping Gxxx headers to '{{ swversion_stdout }}'
  lineinfile:
    line: "AVAYA BRANCH GATEWAY,Latest,Gxxx,,{{ latest_gxxx_appsp }},,, }}"
    insertafter: EOF
    dest: "{{ swversion_stdout }}"
  delegate_to: localhost
  tags:
    - gxxx

- name: Dumping Gxxx versions to '{{ swversion_stdout }}'
  vars:
    pgrp: "{{ group_names | first | default('') }}"
    cgrp: "{{ group_names | last | default('') }}"
    ssp: ""
    ksp: ""
  lineinfile:
    line: "{{ inventory_hostname }},{{ ansible_host }},{{ pgrp }},{{ cgrp }},{{ appsp }},{{ syssp }},{{ ssp }},{{ ksp }}"
    insertafter: EOF
    dest: "{{ swversion_stdout }}"
  delegate_to: localhost
  ignore_errors: true
  tags:
    - gxxx
...