---
- name: Setting ansible_ssh_common_args when ssh_proxy is defined
  set_fact:
    ansible_ssh_common_args: "{{ ssh_args }}"
  when: ssh_proxy is defined
  tags:
  - ssh_proxy

- name: Obtaining `ipcs-version` from {{ inventory_hostname }}
  shell: "sudo /usr/local/ipcs/icu/scripts/ipcs-version"
  register: ipcs_version_output
  tags:
  - swversion

- name: Setting 'swversion' fact for {{ inventory_hostname }}
  set_fact:
    swversion: "{{ ipcs_version_output.stdout }}"
    cacheable: yes
  tags:
  - swversion

- name: Obtaining `EASGStatus` from {{ inventory_hostname }}
  shell: "echo $(/usr/bin/EASGStatus) 2>/dev/null"
  register: EASGStatus_output
  tags:
  - easg

- name: Setting 'EASGStatus' fact for {{ inventory_hostname }}
  set_fact:
    EASGStatus: "{{ EASGStatus_output.stdout }}"
    cacheable: yes
  tags:
  - easg

- name: Obtaining `sysinfo` file from {{ inventory_hostname }}
  become: yes
  slurp:
    src: /usr/local/ipcs/etc/sysinfo
  register: sysinfo
  when: ansible_become_pass is defined
  tags:
  - status

- name: Setting 'sysinfo' fact for {{ inventory_hostname }}
  set_fact:
    sysinfo: "{{ sysinfo['content'] | b64decode }}"
    cacheable: yes
  when: ansible_become_pass is defined
  tags:
  - status

- name: Obtaining backup_servers from {{ inventory_hostname }} database
  become: yes
  vars:
    sql: >
      "SELECT
        name,
        user_name,
        address,
        location
      FROM sftp_servers"
  shell: "psql -t -U postgres {{ item }} -AtF',' -c {{ sql }}"
  register: sftp_servers_output
  with_items:
    - commondb
    - sbcedb
  when: ansible_become_pass is defined
  tags:
  - backup

- name: Setting 'backup_config' fact for {{ inventory_hostname }}
  vars:
    keys_list: ['server_name', 'user_name', 'ip_port', 'path']
  set_fact:
    backup_config: "{{ backup_config | default({}) | combine({ item.item: dict(keys_list | zip(item.stdout | split(','))) }) }}"
  with_items:
    - "{{ sftp_servers_output.results }}"
  when: ansible_become_pass is defined
  tags:
  - backup

- name: Obtaining `gui_config` from {{ inventory_hostname }} database
  become: yes
  vars:
    sql: >
      "SELECT * 
      FROM gui_config
      WHERE name LIKE 'RESTORE%'"
  shell: "psql -t -U postgres {{ item }} -AtF',' -c {{ sql }}"
  register: gui_config_output
  when: ansible_become_pass is defined
  with_items:
    - commondb
    - sbcedb
  tags:
  - backup

- name: Creating 'backup_frequency' fact for {{ inventory_hostname }}
  set_fact:
    backup_frequency: "{{ backup_frequency | default({}) | combine({ item.item: dict({ 'freq': item.stdout_lines }) }, recursive=True) }}"
  when: ansible_become_pass is defined
  with_items: "{{ gui_config_output.results }}"
  tags:
  - backup

- name: Setting 'backup_config' fact for {{ inventory_hostname }}
  set_fact:
    backup_config: "{{ backup_config | combine(backup_frequency, recursive=True) }}"
  with_dict: "{{ backup_frequency }}"
  when: ansible_become_pass is defined
  tags:
  - backup

- name: Setting 'backup' fact for {{ inventory_hostname }}
  set_fact:
    backup: "{{ backup | default({}) | combine({ 'config' : backup_config }) }}"
    cacheable: yes
  with_dict: "{{ backup_frequency }}"
  when: ansible_become_pass is defined
  tags:
  - backup

- name: Obtaining backup history from {{ inventory_hostname }}
  become: yes
  slurp:
    src: "/usr/local/ipcs/snapshots/repo.xml"
  register: backup_history_output
  when: ansible_become_pass is defined
  tags:
  - backup

- name: Updating 'backup' fact for {{ inventory_hostname }}
  set_fact:
    backup: "{{ backup | combine({ 'history': backup_history_output['content'] | b64decode }) }}"
    cacheable: yes
  when: ansible_become_pass is defined
  tags:
  - backup

- name: Obtaining active alarms from {{ inventory_hostname }} database
  become: yes
  vars:
    sql: >
      "SELECT
        to_timestamp(alarm_timestampsecs/1000) as date,
        trap_severity_level as severity,
        alarm_notes as description
      FROM alarms
      ORDER BY alarm_timestampsecs DESC
      LIMIT 10"
  shell: "/bin/psql -U postgres {{ item }} --pset='footer=off' -AqF',' -c {{ sql }}"
  when: ansible_become_pass is defined
  register: alarms_output
  with_items:
    - commondb
    - sbcedb
  tags:
  - alarms

- name: Setting 'alarms' fact for {{ inventory_hostname }}
  set_fact:
    alarms: "{{ alarms | default({}) | combine({ item.item: item.stdout }) }}"
    cacheable: yes
  with_items:
    - "{{ alarms_output.results }}"
  when: ansible_become_pass is defined
  tags:
  - alarms

- name: Getting the list of certificates from {{ inventory_hostname }}
  become: yes
  find:
    paths: "/usr/local/ipcs/cert/certificate/"
  register: certificate_list
  when: ansible_become_pass is defined
  tags:
  - certificates

- name: Obtaining certificates from {{ inventory_hostname }}
  become: yes
  slurp:
    src: '{{ item.path }}'
  register: certificates_files
  with_items: "{{ certificate_list.files }}"
  tags:
  - certificates

- name: Adding certificates to 'certificates' fact for {{ inventory_hostname }}
  set_fact:
    certificates: "{{ certificates | default({}) | combine({ item['source'] | basename : item['content'] | b64decode | split_pem }) }}"
    cacheable: yes
  with_items:
    - "{{ certificates_files.results }}"
  tags:
  - certificates
...