---
- name: Setting ansible_ssh_common_args when ssh_proxy is defined
  set_fact:
    ansible_ssh_common_args: "{{ ssh_args }}"
  when: ssh_proxy is defined
  tags:
  - ssh_proxy

- name: Obtaining `swversion` from {{ inventory_hostname }}
  shell: "/opt/mvap/bin/swversion"
  register: swversion_output
  tags:
  - swversion

- name: Setting 'swversion' fact for {{ inventory_hostname }}
  set_fact:
    swversion: "{{ swversion_output.stdout }}"
    cacheable: yes
  tags:
  - swversion

- name: Obtaining `EASGStatus` from {{ inventory_hostname }}
  shell: "echo $(/usr/bin/EASGStatus)"
  register: EASGStatus_output
  tags:
  - easg

- name: Setting 'EASGStatus' fact for {{ inventory_hostname }}
  set_fact:
    EASGStatus: "{{ EASGStatus_output.stdout }}"
    cacheable: yes
  tags:
  - easg

- name: Obtaining `scheduleRemoteBackUp status` from {{ inventory_hostname }}
  become: yes
  shell: "/opt/mvap/bin/scheduleRemoteBackUp status"
  register: backup_config_output
  when: ansible_become_pass is defined
  tags:
  - backup

- name: Setting 'backup' fact for {{ inventory_hostname }}
  set_fact:
    backup: "{{ backup | default({}) | combine({ 'config': backup_config_output.stdout }) }}"
    cacheable: yes
  when: ansible_become_pass is defined
  tags:
  - backup

- name: Obtaining `/opt/mvap/bin/mvap.sh info` from {{ inventory_hostname }}
  shell: "/opt/mvap/bin/mvap.sh info"
  register: mvap_info_output
  tags:
  - status
  - licenses

- name: Setting 'mvap_info' fact for {{ inventory_hostname }}
  set_fact:
    mvap_info: "{{ mvap_info_output.stdout }}"
    cacheable: yes
  tags:
  - status
  - licenses

- name: Obtaining last alarms from {{ inventory_hostname }}
  shell: "ls -tr /var/log/avaya/aes/alarm.log* | xargs zcat | grep O_ | tail"
  register: alarms_output
  tags:
  - alarms

- name: Setting 'alarms' fact for {{ inventory_hostname }}
  set_fact:
    alarms: "{{ alarms_output.stdout }}"
    cacheable: yes
  tags:
  - alarms

- name: Obtaining certificates from {{ inventory_hostname }}
  get_certs:
    name: "{{ item.name }}"
    host: "{{ item.host }}"
    port: "{{ item.port }}"
    starttls: "{{ item.starttls }}"
  with_items:
    - { name: "web", host: "{{ ansible_host }}", port: 443 , starttls: "" }
  register: get_certs_output
  tags:
  - certificates

- name: Setting 'certificates' fact for {{ inventory_hostname }}
  set_fact:
    certificates: "{{ certificates | default({}) | combine({ item.1: get_certs_output.results[item.0][item.1] }) }}"
    cacheable: yes
  with_indexed_items:
    - "web"
  tags:
  - certificates
...