---
- name: Setting ansible_ssh_common_args when ssh_proxy is defined
  set_fact:
    ansible_ssh_common_args: "{{ ssh_args }}"
  when: ssh_proxy is defined
  tags:
  - ssh_proxy

- name: Obtaining `svc amm swversion` from {{ inventory_hostname }}
  shell: "/opt/Avaya/bin/sys/alias-wrappers/svc-wrapper.sh amm swversion"
  register: swversion_output
  tags:
  - swversion

- name: Setting 'swversion' fact for {{ inventory_hostname }}
  set_fact:
    swversion: "{{ swversion_output.stdout }}"
    cacheable: yes
  tags:
  - swversion

- name: Obtaining `sys versions` from {{ inventory_hostname }}
  shell: "/opt/Avaya/bin/sys/alias-wrappers/sys-wrapper.sh versions"
  register: sysversions_output
  tags:
  - swversion

- name: Updating 'swversion' fact for {{ inventory_hostname }}
  set_fact:
    swversion: "{{ '\n'.join((swversion, sysversions_output.stdout)) }}"
    cacheable: yes
  when: sysversions_output.stdout is defined
  tags:
  - swversion

- name: Obtaining `EASGStatus` from {{ inventory_hostname }}
  shell: "echo $(/usr/bin/EASGStatus)"
  register: EASGStatus_output
  tags:
  - easg

- name: Setting 'EASGStatus' fact for {{ inventory_hostname }}
  set_fact:
    EASGStatus: "{{ EASGStatus_output.stdout }}"
    cacheable: yes
  tags:
  - easg

- name: Obtaining `svc amm status` from {{ inventory_hostname }}
  shell: "/opt/Avaya/bin/sys/alias-wrappers/svc-wrapper.sh amm status"
  register: svc_amm_status_output
  tags:
  - status

- name: Setting 'svc_amm_status' fact for {{ inventory_hostname }}
  set_fact:
    svc_amm_status: "{{ svc_amm_status_output.stdout }}"
    cacheable: yes
  tags:
  - status

- name: Obtaining backup history from {{ inventory_hostname }}
  shell: ". /opt/Avaya/bin/sys/alias-wrappers/cdto-wrapper.sh logs; ls -tr AMM_utility* | xargs grep 'Backup:  Name:' | sort | uniq | tail"
  register: amm_backup_history_output
  tags:
  - backup

- name: Updating 'backup' fact with 'history' for {{ inventory_hostname }}
  set_fact:
    backup: "{{ backup | default({}) | combine({ 'history': amm_backup_history_output.stdout }) }}"
    cacheable: yes
  when: amm_backup_history_output is defined and amm_backup_history_output.stdout != ""
  tags:
  - backup

- name: Obtaining certificates from {{ inventory_hostname }}
  get_certs:
    name: "{{ item.name }}"
    host: "{{ item.host }}"
    port: "{{ item.port }}"
    starttls: "{{ item.starttls }}"
  with_items:
    - { name: "application", host: "{{ ansible_host }}", port: 8443, starttls: "" }
    - { name: "internal", host: "{{ ansible_host }}", port: 8448, starttls: "" }
    - { name: "oam", host: "{{ ansible_host }}", port: 8445, starttls: "" }
  register: get_certs_output
  tags:
  - certificates

- name: Setting 'certificates' fact for {{ inventory_hostname }}
  set_fact:
    certificates: "{{ certificates | default({}) | combine({ item.1: get_certs_output.results[item.0][item.1] }) }}"
    cacheable: yes
  with_indexed_items:
    - "application"
    - "internal"
    - "oam"
  tags:
  - certificates
...