---
- name: Setting ansible_ssh_common_args when ssh_proxy is defined
  set_fact:
    ansible_ssh_common_args: "{{ ssh_args }}"
  when: ssh_proxy is defined
  tags:
  - ssh_proxy

- name: Obtaining `svc csa swversion` from {{ inventory_hostname }}
  shell: "/opt/Avaya/bin/sys/alias-wrappers/svc-wrapper.sh csa swversion"
  register: swversion_output
  tags:
  - swversion

- name: Setting 'swversion' fact for {{ inventory_hostname }}
  set_fact:
    swversion: "{{ swversion_output.stdout }}"
    cacheable: yes
  tags:
  - swversion

- name: Obtaining `sysUpdate --status` from {{ inventory_hostname }}
  shell: "sudo /opt/sys-update/sysUpdate.sh --status"
  register: sysUpdate_output
  timeout: 5
  tags:
  - swversion

- name: Updating 'swversion' fact for {{ inventory_hostname }}
  set_fact:
    swversion: "{{ '\n'.join((swversion, sysUpdate_output.stdout)) }}"
    cacheable: yes
  when: sysUpdate_output.stdout is defined
  tags:
  - swversion

- name: Obtaining `EASGStatus` from {{ inventory_hostname }}
  shell: "echo $(/usr/bin/EASGStatus)"
  register: EASGStatus_output
  tags:
  - easg

- name: Setting 'EASGStatus' fact for {{ inventory_hostname }}
  set_fact:
    EASGStatus: "{{ EASGStatus_output.stdout }}"
    cacheable: yes
  tags:
  - easg

- name: Obtaining `svc csa status` from {{ inventory_hostname }}
  shell: "/opt/Avaya/bin/sys/alias-wrappers/svc-wrapper.sh csa status"
  register: svc_csa_status_output
  tags:
  - status

- name: Setting 'svc_csa_status' fact for {{ inventory_hostname }}
  set_fact:
    svc_aads_status: "{{ svc_csa_status_output.stdout }}"
    cacheable: yes
  tags:
  - status

- name: Obtaining automatic backup history from {{ inventory_hostname }}
  shell: "ls -ltrd /var/log/Avaya/backup/* | tail"
  register: aawg_auto_backup_history_output
  tags:
  - backup

- name: Setting 'backup' fact with 'auto' for {{ inventory_hostname }}
  set_fact:
    backup: "{{ backup | default({}) | combine({ 'history': dict({ 'auto': aawg_auto_backup_history_output.stdout }) }) }}"
    cacheable: yes
  when: aawg_auto_backup_history_output is defined and aawg_auto_backup_history_output.stdout != ""
  tags:
  - backup

- name: Obtaining all backup history from {{ inventory_hostname }}
  shell: ". /opt/Avaya/bin/sys/alias-wrappers/cdto-wrapper.sh logs; ls -tr CSA_utility* | xargs grep 'Backup:  Name:' | tail"
  register: aawg_all_backup_history_output
  tags:
  - backup

- name: Updating 'backup' fact with 'all' for {{ inventory_hostname }}
  set_fact:
    backup: "{{ backup | default({}) | combine({ 'history': dict({ 'all': aawg_all_backup_history_output.stdout }) }, recursive=True) }}"
    cacheable: yes
  when: aawg_all_backup_history_output is defined and aawg_all_backup_history_output.stdout != ""
  tags:
  - backup

- name: Obtaining certificates from {{ inventory_hostname }}
  get_certs:
    name: "{{ item.name }}"
    host: "{{ item.host }}"
    port: "{{ item.port }}"
    starttls: "{{ item.starttls }}"
  with_items:
    - { name: "application", host: "{{ ansible_host }}", port: 5061, starttls: "" }
    - { name: "internal", host: "{{ ansible_host }}", port: 8445, starttls: "" }
  register: get_certs_output
  tags:
  - certificates

- name: Setting 'certificates' fact for {{ inventory_hostname }}
  set_fact:
    certificates: "{{ certificates | default({}) | combine({ item.1: get_certs_output.results[item.0][item.1] }) }}"
    cacheable: yes
  with_indexed_items:
    - "application"
    - "internal"
  tags:
  - certificates
...